/*
Firefly III API v2.0.4

This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2023-06-11T09:14:35+00:00 

API version: 2.0.4
Contact: james@firefly-iii.org
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
)

// checks if the Rule type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Rule{}

// Rule struct for Rule
type Rule struct {
	CreatedAt *time.Time `json:"created_at,omitempty"`
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
	Title string `json:"title"`
	Description *string `json:"description,omitempty"`
	// ID of the rule group under which the rule must be stored. Either this field or rule_group_title is mandatory.
	RuleGroupId string `json:"rule_group_id"`
	// Title of the rule group under which the rule must be stored. Either this field or rule_group_id is mandatory.
	RuleGroupTitle *string `json:"rule_group_title,omitempty"`
	Order *int32 `json:"order,omitempty"`
	Trigger RuleTriggerType `json:"trigger"`
	// Whether or not the rule is even active. Default is true.
	Active *bool `json:"active,omitempty"`
	// If the rule is set to be strict, ALL triggers must hit in order for the rule to fire. Otherwise, just one is enough. Default value is true.
	Strict *bool `json:"strict,omitempty"`
	// If this value is true and the rule is triggered, other rules  after this one in the group will be skipped. Default value is false.
	StopProcessing *bool `json:"stop_processing,omitempty"`
	Triggers []RuleTrigger `json:"triggers"`
	Actions []RuleAction `json:"actions"`
}

// NewRule instantiates a new Rule object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRule(title string, ruleGroupId string, trigger RuleTriggerType, triggers []RuleTrigger, actions []RuleAction) *Rule {
	this := Rule{}
	this.Title = title
	this.RuleGroupId = ruleGroupId
	this.Trigger = trigger
	var active bool = true
	this.Active = &active
	var stopProcessing bool = false
	this.StopProcessing = &stopProcessing
	this.Triggers = triggers
	this.Actions = actions
	return &this
}

// NewRuleWithDefaults instantiates a new Rule object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRuleWithDefaults() *Rule {
	this := Rule{}
	var active bool = true
	this.Active = &active
	var stopProcessing bool = false
	this.StopProcessing = &stopProcessing
	return &this
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *Rule) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Rule) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *Rule) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *Rule) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *Rule) GetUpdatedAt() time.Time {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Rule) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *Rule) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given time.Time and assigns it to the UpdatedAt field.
func (o *Rule) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = &v
}

// GetTitle returns the Title field value
func (o *Rule) GetTitle() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Title
}

// GetTitleOk returns a tuple with the Title field value
// and a boolean to check if the value has been set.
func (o *Rule) GetTitleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Title, true
}

// SetTitle sets field value
func (o *Rule) SetTitle(v string) {
	o.Title = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *Rule) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Rule) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *Rule) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *Rule) SetDescription(v string) {
	o.Description = &v
}

// GetRuleGroupId returns the RuleGroupId field value
func (o *Rule) GetRuleGroupId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RuleGroupId
}

// GetRuleGroupIdOk returns a tuple with the RuleGroupId field value
// and a boolean to check if the value has been set.
func (o *Rule) GetRuleGroupIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RuleGroupId, true
}

// SetRuleGroupId sets field value
func (o *Rule) SetRuleGroupId(v string) {
	o.RuleGroupId = v
}

// GetRuleGroupTitle returns the RuleGroupTitle field value if set, zero value otherwise.
func (o *Rule) GetRuleGroupTitle() string {
	if o == nil || IsNil(o.RuleGroupTitle) {
		var ret string
		return ret
	}
	return *o.RuleGroupTitle
}

// GetRuleGroupTitleOk returns a tuple with the RuleGroupTitle field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Rule) GetRuleGroupTitleOk() (*string, bool) {
	if o == nil || IsNil(o.RuleGroupTitle) {
		return nil, false
	}
	return o.RuleGroupTitle, true
}

// HasRuleGroupTitle returns a boolean if a field has been set.
func (o *Rule) HasRuleGroupTitle() bool {
	if o != nil && !IsNil(o.RuleGroupTitle) {
		return true
	}

	return false
}

// SetRuleGroupTitle gets a reference to the given string and assigns it to the RuleGroupTitle field.
func (o *Rule) SetRuleGroupTitle(v string) {
	o.RuleGroupTitle = &v
}

// GetOrder returns the Order field value if set, zero value otherwise.
func (o *Rule) GetOrder() int32 {
	if o == nil || IsNil(o.Order) {
		var ret int32
		return ret
	}
	return *o.Order
}

// GetOrderOk returns a tuple with the Order field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Rule) GetOrderOk() (*int32, bool) {
	if o == nil || IsNil(o.Order) {
		return nil, false
	}
	return o.Order, true
}

// HasOrder returns a boolean if a field has been set.
func (o *Rule) HasOrder() bool {
	if o != nil && !IsNil(o.Order) {
		return true
	}

	return false
}

// SetOrder gets a reference to the given int32 and assigns it to the Order field.
func (o *Rule) SetOrder(v int32) {
	o.Order = &v
}

// GetTrigger returns the Trigger field value
func (o *Rule) GetTrigger() RuleTriggerType {
	if o == nil {
		var ret RuleTriggerType
		return ret
	}

	return o.Trigger
}

// GetTriggerOk returns a tuple with the Trigger field value
// and a boolean to check if the value has been set.
func (o *Rule) GetTriggerOk() (*RuleTriggerType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Trigger, true
}

// SetTrigger sets field value
func (o *Rule) SetTrigger(v RuleTriggerType) {
	o.Trigger = v
}

// GetActive returns the Active field value if set, zero value otherwise.
func (o *Rule) GetActive() bool {
	if o == nil || IsNil(o.Active) {
		var ret bool
		return ret
	}
	return *o.Active
}

// GetActiveOk returns a tuple with the Active field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Rule) GetActiveOk() (*bool, bool) {
	if o == nil || IsNil(o.Active) {
		return nil, false
	}
	return o.Active, true
}

// HasActive returns a boolean if a field has been set.
func (o *Rule) HasActive() bool {
	if o != nil && !IsNil(o.Active) {
		return true
	}

	return false
}

// SetActive gets a reference to the given bool and assigns it to the Active field.
func (o *Rule) SetActive(v bool) {
	o.Active = &v
}

// GetStrict returns the Strict field value if set, zero value otherwise.
func (o *Rule) GetStrict() bool {
	if o == nil || IsNil(o.Strict) {
		var ret bool
		return ret
	}
	return *o.Strict
}

// GetStrictOk returns a tuple with the Strict field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Rule) GetStrictOk() (*bool, bool) {
	if o == nil || IsNil(o.Strict) {
		return nil, false
	}
	return o.Strict, true
}

// HasStrict returns a boolean if a field has been set.
func (o *Rule) HasStrict() bool {
	if o != nil && !IsNil(o.Strict) {
		return true
	}

	return false
}

// SetStrict gets a reference to the given bool and assigns it to the Strict field.
func (o *Rule) SetStrict(v bool) {
	o.Strict = &v
}

// GetStopProcessing returns the StopProcessing field value if set, zero value otherwise.
func (o *Rule) GetStopProcessing() bool {
	if o == nil || IsNil(o.StopProcessing) {
		var ret bool
		return ret
	}
	return *o.StopProcessing
}

// GetStopProcessingOk returns a tuple with the StopProcessing field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Rule) GetStopProcessingOk() (*bool, bool) {
	if o == nil || IsNil(o.StopProcessing) {
		return nil, false
	}
	return o.StopProcessing, true
}

// HasStopProcessing returns a boolean if a field has been set.
func (o *Rule) HasStopProcessing() bool {
	if o != nil && !IsNil(o.StopProcessing) {
		return true
	}

	return false
}

// SetStopProcessing gets a reference to the given bool and assigns it to the StopProcessing field.
func (o *Rule) SetStopProcessing(v bool) {
	o.StopProcessing = &v
}

// GetTriggers returns the Triggers field value
func (o *Rule) GetTriggers() []RuleTrigger {
	if o == nil {
		var ret []RuleTrigger
		return ret
	}

	return o.Triggers
}

// GetTriggersOk returns a tuple with the Triggers field value
// and a boolean to check if the value has been set.
func (o *Rule) GetTriggersOk() ([]RuleTrigger, bool) {
	if o == nil {
		return nil, false
	}
	return o.Triggers, true
}

// SetTriggers sets field value
func (o *Rule) SetTriggers(v []RuleTrigger) {
	o.Triggers = v
}

// GetActions returns the Actions field value
func (o *Rule) GetActions() []RuleAction {
	if o == nil {
		var ret []RuleAction
		return ret
	}

	return o.Actions
}

// GetActionsOk returns a tuple with the Actions field value
// and a boolean to check if the value has been set.
func (o *Rule) GetActionsOk() ([]RuleAction, bool) {
	if o == nil {
		return nil, false
	}
	return o.Actions, true
}

// SetActions sets field value
func (o *Rule) SetActions(v []RuleAction) {
	o.Actions = v
}

func (o Rule) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Rule) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	// skip: created_at is readOnly
	// skip: updated_at is readOnly
	toSerialize["title"] = o.Title
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	toSerialize["rule_group_id"] = o.RuleGroupId
	if !IsNil(o.RuleGroupTitle) {
		toSerialize["rule_group_title"] = o.RuleGroupTitle
	}
	// skip: order is readOnly
	toSerialize["trigger"] = o.Trigger
	if !IsNil(o.Active) {
		toSerialize["active"] = o.Active
	}
	if !IsNil(o.Strict) {
		toSerialize["strict"] = o.Strict
	}
	if !IsNil(o.StopProcessing) {
		toSerialize["stop_processing"] = o.StopProcessing
	}
	toSerialize["triggers"] = o.Triggers
	toSerialize["actions"] = o.Actions
	return toSerialize, nil
}

type NullableRule struct {
	value *Rule
	isSet bool
}

func (v NullableRule) Get() *Rule {
	return v.value
}

func (v *NullableRule) Set(val *Rule) {
	v.value = val
	v.isSet = true
}

func (v NullableRule) IsSet() bool {
	return v.isSet
}

func (v *NullableRule) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRule(val *Rule) *NullableRule {
	return &NullableRule{value: val, isSet: true}
}

func (v NullableRule) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRule) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


