/*
Firefly III API v2.0.4

This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2023-06-11T09:14:35+00:00 

API version: 2.0.4
Contact: james@firefly-iii.org
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ConfigurationSingle type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConfigurationSingle{}

// ConfigurationSingle struct for ConfigurationSingle
type ConfigurationSingle struct {
	Data Configuration `json:"data"`
}

// NewConfigurationSingle instantiates a new ConfigurationSingle object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConfigurationSingle(data Configuration) *ConfigurationSingle {
	this := ConfigurationSingle{}
	this.Data = data
	return &this
}

// NewConfigurationSingleWithDefaults instantiates a new ConfigurationSingle object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConfigurationSingleWithDefaults() *ConfigurationSingle {
	this := ConfigurationSingle{}
	return &this
}

// GetData returns the Data field value
func (o *ConfigurationSingle) GetData() Configuration {
	if o == nil {
		var ret Configuration
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *ConfigurationSingle) GetDataOk() (*Configuration, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *ConfigurationSingle) SetData(v Configuration) {
	o.Data = v
}

func (o ConfigurationSingle) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConfigurationSingle) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

type NullableConfigurationSingle struct {
	value *ConfigurationSingle
	isSet bool
}

func (v NullableConfigurationSingle) Get() *ConfigurationSingle {
	return v.value
}

func (v *NullableConfigurationSingle) Set(val *ConfigurationSingle) {
	v.value = val
	v.isSet = true
}

func (v NullableConfigurationSingle) IsSet() bool {
	return v.isSet
}

func (v *NullableConfigurationSingle) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConfigurationSingle(val *ConfigurationSingle) *NullableConfigurationSingle {
	return &NullableConfigurationSingle{value: val, isSet: true}
}

func (v NullableConfigurationSingle) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConfigurationSingle) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


