/*
Firefly III API v2.0.4

This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2023-06-11T09:14:35+00:00 

API version: 2.0.4
Contact: james@firefly-iii.org
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the CategoryStore type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CategoryStore{}

// CategoryStore struct for CategoryStore
type CategoryStore struct {
	Name string `json:"name"`
	Notes NullableString `json:"notes,omitempty"`
}

// NewCategoryStore instantiates a new CategoryStore object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCategoryStore(name string) *CategoryStore {
	this := CategoryStore{}
	this.Name = name
	return &this
}

// NewCategoryStoreWithDefaults instantiates a new CategoryStore object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCategoryStoreWithDefaults() *CategoryStore {
	this := CategoryStore{}
	return &this
}

// GetName returns the Name field value
func (o *CategoryStore) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CategoryStore) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CategoryStore) SetName(v string) {
	o.Name = v
}

// GetNotes returns the Notes field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CategoryStore) GetNotes() string {
	if o == nil || IsNil(o.Notes.Get()) {
		var ret string
		return ret
	}
	return *o.Notes.Get()
}

// GetNotesOk returns a tuple with the Notes field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CategoryStore) GetNotesOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Notes.Get(), o.Notes.IsSet()
}

// HasNotes returns a boolean if a field has been set.
func (o *CategoryStore) HasNotes() bool {
	if o != nil && o.Notes.IsSet() {
		return true
	}

	return false
}

// SetNotes gets a reference to the given NullableString and assigns it to the Notes field.
func (o *CategoryStore) SetNotes(v string) {
	o.Notes.Set(&v)
}
// SetNotesNil sets the value for Notes to be an explicit nil
func (o *CategoryStore) SetNotesNil() {
	o.Notes.Set(nil)
}

// UnsetNotes ensures that no value is present for Notes, not even an explicit nil
func (o *CategoryStore) UnsetNotes() {
	o.Notes.Unset()
}

func (o CategoryStore) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CategoryStore) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	if o.Notes.IsSet() {
		toSerialize["notes"] = o.Notes.Get()
	}
	return toSerialize, nil
}

type NullableCategoryStore struct {
	value *CategoryStore
	isSet bool
}

func (v NullableCategoryStore) Get() *CategoryStore {
	return v.value
}

func (v *NullableCategoryStore) Set(val *CategoryStore) {
	v.value = val
	v.isSet = true
}

func (v NullableCategoryStore) IsSet() bool {
	return v.isSet
}

func (v *NullableCategoryStore) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCategoryStore(val *CategoryStore) *NullableCategoryStore {
	return &NullableCategoryStore{value: val, isSet: true}
}

func (v NullableCategoryStore) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCategoryStore) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


