/*
Firefly III API v2.0.4

This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2023-06-11T09:14:35+00:00 

API version: 2.0.4
Contact: james@firefly-iii.org
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the PiggyBankRead type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PiggyBankRead{}

// PiggyBankRead struct for PiggyBankRead
type PiggyBankRead struct {
	// Immutable value
	Type string `json:"type"`
	Id string `json:"id"`
	Attributes PiggyBank `json:"attributes"`
	Links ObjectLink `json:"links"`
}

// NewPiggyBankRead instantiates a new PiggyBankRead object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPiggyBankRead(type_ string, id string, attributes PiggyBank, links ObjectLink) *PiggyBankRead {
	this := PiggyBankRead{}
	this.Type = type_
	this.Id = id
	this.Attributes = attributes
	this.Links = links
	return &this
}

// NewPiggyBankReadWithDefaults instantiates a new PiggyBankRead object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPiggyBankReadWithDefaults() *PiggyBankRead {
	this := PiggyBankRead{}
	return &this
}

// GetType returns the Type field value
func (o *PiggyBankRead) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *PiggyBankRead) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *PiggyBankRead) SetType(v string) {
	o.Type = v
}

// GetId returns the Id field value
func (o *PiggyBankRead) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *PiggyBankRead) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *PiggyBankRead) SetId(v string) {
	o.Id = v
}

// GetAttributes returns the Attributes field value
func (o *PiggyBankRead) GetAttributes() PiggyBank {
	if o == nil {
		var ret PiggyBank
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *PiggyBankRead) GetAttributesOk() (*PiggyBank, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *PiggyBankRead) SetAttributes(v PiggyBank) {
	o.Attributes = v
}

// GetLinks returns the Links field value
func (o *PiggyBankRead) GetLinks() ObjectLink {
	if o == nil {
		var ret ObjectLink
		return ret
	}

	return o.Links
}

// GetLinksOk returns a tuple with the Links field value
// and a boolean to check if the value has been set.
func (o *PiggyBankRead) GetLinksOk() (*ObjectLink, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Links, true
}

// SetLinks sets field value
func (o *PiggyBankRead) SetLinks(v ObjectLink) {
	o.Links = v
}

func (o PiggyBankRead) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PiggyBankRead) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["id"] = o.Id
	toSerialize["attributes"] = o.Attributes
	toSerialize["links"] = o.Links
	return toSerialize, nil
}

type NullablePiggyBankRead struct {
	value *PiggyBankRead
	isSet bool
}

func (v NullablePiggyBankRead) Get() *PiggyBankRead {
	return v.value
}

func (v *NullablePiggyBankRead) Set(val *PiggyBankRead) {
	v.value = val
	v.isSet = true
}

func (v NullablePiggyBankRead) IsSet() bool {
	return v.isSet
}

func (v *NullablePiggyBankRead) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePiggyBankRead(val *PiggyBankRead) *NullablePiggyBankRead {
	return &NullablePiggyBankRead{value: val, isSet: true}
}

func (v NullablePiggyBankRead) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePiggyBankRead) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


