/*
Firefly III API v2.0.4

This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2023-06-11T09:14:35+00:00 

API version: 2.0.4
Contact: james@firefly-iii.org
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the WebhookAttemptSingle type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WebhookAttemptSingle{}

// WebhookAttemptSingle struct for WebhookAttemptSingle
type WebhookAttemptSingle struct {
	Data WebhookAttemptRead `json:"data"`
}

// NewWebhookAttemptSingle instantiates a new WebhookAttemptSingle object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWebhookAttemptSingle(data WebhookAttemptRead) *WebhookAttemptSingle {
	this := WebhookAttemptSingle{}
	this.Data = data
	return &this
}

// NewWebhookAttemptSingleWithDefaults instantiates a new WebhookAttemptSingle object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWebhookAttemptSingleWithDefaults() *WebhookAttemptSingle {
	this := WebhookAttemptSingle{}
	return &this
}

// GetData returns the Data field value
func (o *WebhookAttemptSingle) GetData() WebhookAttemptRead {
	if o == nil {
		var ret WebhookAttemptRead
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *WebhookAttemptSingle) GetDataOk() (*WebhookAttemptRead, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *WebhookAttemptSingle) SetData(v WebhookAttemptRead) {
	o.Data = v
}

func (o WebhookAttemptSingle) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WebhookAttemptSingle) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

type NullableWebhookAttemptSingle struct {
	value *WebhookAttemptSingle
	isSet bool
}

func (v NullableWebhookAttemptSingle) Get() *WebhookAttemptSingle {
	return v.value
}

func (v *NullableWebhookAttemptSingle) Set(val *WebhookAttemptSingle) {
	v.value = val
	v.isSet = true
}

func (v NullableWebhookAttemptSingle) IsSet() bool {
	return v.isSet
}

func (v *NullableWebhookAttemptSingle) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWebhookAttemptSingle(val *WebhookAttemptSingle) *NullableWebhookAttemptSingle {
	return &NullableWebhookAttemptSingle{value: val, isSet: true}
}

func (v NullableWebhookAttemptSingle) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWebhookAttemptSingle) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


