/*
Firefly III API v2.0.4

This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2023-06-11T09:14:35+00:00 

API version: 2.0.4
Contact: james@firefly-iii.org
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the Unauthenticated type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Unauthenticated{}

// Unauthenticated struct for Unauthenticated
type Unauthenticated struct {
	Message *string `json:"message,omitempty"`
	Exception *string `json:"exception,omitempty"`
}

// NewUnauthenticated instantiates a new Unauthenticated object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUnauthenticated() *Unauthenticated {
	this := Unauthenticated{}
	return &this
}

// NewUnauthenticatedWithDefaults instantiates a new Unauthenticated object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUnauthenticatedWithDefaults() *Unauthenticated {
	this := Unauthenticated{}
	return &this
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *Unauthenticated) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Unauthenticated) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *Unauthenticated) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *Unauthenticated) SetMessage(v string) {
	o.Message = &v
}

// GetException returns the Exception field value if set, zero value otherwise.
func (o *Unauthenticated) GetException() string {
	if o == nil || IsNil(o.Exception) {
		var ret string
		return ret
	}
	return *o.Exception
}

// GetExceptionOk returns a tuple with the Exception field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Unauthenticated) GetExceptionOk() (*string, bool) {
	if o == nil || IsNil(o.Exception) {
		return nil, false
	}
	return o.Exception, true
}

// HasException returns a boolean if a field has been set.
func (o *Unauthenticated) HasException() bool {
	if o != nil && !IsNil(o.Exception) {
		return true
	}

	return false
}

// SetException gets a reference to the given string and assigns it to the Exception field.
func (o *Unauthenticated) SetException(v string) {
	o.Exception = &v
}

func (o Unauthenticated) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Unauthenticated) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.Exception) {
		toSerialize["exception"] = o.Exception
	}
	return toSerialize, nil
}

type NullableUnauthenticated struct {
	value *Unauthenticated
	isSet bool
}

func (v NullableUnauthenticated) Get() *Unauthenticated {
	return v.value
}

func (v *NullableUnauthenticated) Set(val *Unauthenticated) {
	v.value = val
	v.isSet = true
}

func (v NullableUnauthenticated) IsSet() bool {
	return v.isSet
}

func (v *NullableUnauthenticated) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUnauthenticated(val *Unauthenticated) *NullableUnauthenticated {
	return &NullableUnauthenticated{value: val, isSet: true}
}

func (v NullableUnauthenticated) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUnauthenticated) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


