/*
Firefly III API v2.0.4

This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2023-06-11T09:14:35+00:00 

API version: 2.0.4
Contact: james@firefly-iii.org
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
)

// checks if the RecurrenceRepetition type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RecurrenceRepetition{}

// RecurrenceRepetition struct for RecurrenceRepetition
type RecurrenceRepetition struct {
	Id *string `json:"id,omitempty"`
	CreatedAt *time.Time `json:"created_at,omitempty"`
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
	Type RecurrenceRepetitionType `json:"type"`
	// Information that defined the type of repetition. - For 'daily', this is empty. - For 'weekly', it is day of the week between 1 and 7 (Monday - Sunday). - For 'ndom', it is '1,2' or '4,5' or something else, where the first number is the week in the month, and the second number is the day in the week (between 1 and 7). '2,3' means: the 2nd Wednesday of the month - For 'monthly' it is the day of the month (1 - 31) - For yearly, it is a full date, ie '2018-09-17'. The year you use does not matter. 
	Moment string `json:"moment"`
	// How many occurrences to skip. 0 means skip nothing. 1 means every other.
	Skip *int32 `json:"skip,omitempty"`
	// How to respond when the recurring transaction falls in the weekend. Possible values: 1. Do nothing, just create it 2. Create no transaction. 3. Skip to the previous Friday. 4. Skip to the next Monday. 
	Weekend *int32 `json:"weekend,omitempty"`
	// Auto-generated repetition description.
	Description *string `json:"description,omitempty"`
	// Array of future dates when the repetition will apply to. Auto generated.
	Occurrences []time.Time `json:"occurrences,omitempty"`
}

// NewRecurrenceRepetition instantiates a new RecurrenceRepetition object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRecurrenceRepetition(type_ RecurrenceRepetitionType, moment string) *RecurrenceRepetition {
	this := RecurrenceRepetition{}
	this.Type = type_
	this.Moment = moment
	return &this
}

// NewRecurrenceRepetitionWithDefaults instantiates a new RecurrenceRepetition object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRecurrenceRepetitionWithDefaults() *RecurrenceRepetition {
	this := RecurrenceRepetition{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *RecurrenceRepetition) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RecurrenceRepetition) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *RecurrenceRepetition) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *RecurrenceRepetition) SetId(v string) {
	o.Id = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *RecurrenceRepetition) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RecurrenceRepetition) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *RecurrenceRepetition) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *RecurrenceRepetition) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *RecurrenceRepetition) GetUpdatedAt() time.Time {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RecurrenceRepetition) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *RecurrenceRepetition) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given time.Time and assigns it to the UpdatedAt field.
func (o *RecurrenceRepetition) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = &v
}

// GetType returns the Type field value
func (o *RecurrenceRepetition) GetType() RecurrenceRepetitionType {
	if o == nil {
		var ret RecurrenceRepetitionType
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *RecurrenceRepetition) GetTypeOk() (*RecurrenceRepetitionType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *RecurrenceRepetition) SetType(v RecurrenceRepetitionType) {
	o.Type = v
}

// GetMoment returns the Moment field value
func (o *RecurrenceRepetition) GetMoment() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Moment
}

// GetMomentOk returns a tuple with the Moment field value
// and a boolean to check if the value has been set.
func (o *RecurrenceRepetition) GetMomentOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Moment, true
}

// SetMoment sets field value
func (o *RecurrenceRepetition) SetMoment(v string) {
	o.Moment = v
}

// GetSkip returns the Skip field value if set, zero value otherwise.
func (o *RecurrenceRepetition) GetSkip() int32 {
	if o == nil || IsNil(o.Skip) {
		var ret int32
		return ret
	}
	return *o.Skip
}

// GetSkipOk returns a tuple with the Skip field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RecurrenceRepetition) GetSkipOk() (*int32, bool) {
	if o == nil || IsNil(o.Skip) {
		return nil, false
	}
	return o.Skip, true
}

// HasSkip returns a boolean if a field has been set.
func (o *RecurrenceRepetition) HasSkip() bool {
	if o != nil && !IsNil(o.Skip) {
		return true
	}

	return false
}

// SetSkip gets a reference to the given int32 and assigns it to the Skip field.
func (o *RecurrenceRepetition) SetSkip(v int32) {
	o.Skip = &v
}

// GetWeekend returns the Weekend field value if set, zero value otherwise.
func (o *RecurrenceRepetition) GetWeekend() int32 {
	if o == nil || IsNil(o.Weekend) {
		var ret int32
		return ret
	}
	return *o.Weekend
}

// GetWeekendOk returns a tuple with the Weekend field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RecurrenceRepetition) GetWeekendOk() (*int32, bool) {
	if o == nil || IsNil(o.Weekend) {
		return nil, false
	}
	return o.Weekend, true
}

// HasWeekend returns a boolean if a field has been set.
func (o *RecurrenceRepetition) HasWeekend() bool {
	if o != nil && !IsNil(o.Weekend) {
		return true
	}

	return false
}

// SetWeekend gets a reference to the given int32 and assigns it to the Weekend field.
func (o *RecurrenceRepetition) SetWeekend(v int32) {
	o.Weekend = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *RecurrenceRepetition) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RecurrenceRepetition) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *RecurrenceRepetition) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *RecurrenceRepetition) SetDescription(v string) {
	o.Description = &v
}

// GetOccurrences returns the Occurrences field value if set, zero value otherwise.
func (o *RecurrenceRepetition) GetOccurrences() []time.Time {
	if o == nil || IsNil(o.Occurrences) {
		var ret []time.Time
		return ret
	}
	return o.Occurrences
}

// GetOccurrencesOk returns a tuple with the Occurrences field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RecurrenceRepetition) GetOccurrencesOk() ([]time.Time, bool) {
	if o == nil || IsNil(o.Occurrences) {
		return nil, false
	}
	return o.Occurrences, true
}

// HasOccurrences returns a boolean if a field has been set.
func (o *RecurrenceRepetition) HasOccurrences() bool {
	if o != nil && !IsNil(o.Occurrences) {
		return true
	}

	return false
}

// SetOccurrences gets a reference to the given []time.Time and assigns it to the Occurrences field.
func (o *RecurrenceRepetition) SetOccurrences(v []time.Time) {
	o.Occurrences = v
}

func (o RecurrenceRepetition) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RecurrenceRepetition) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	// skip: id is readOnly
	// skip: created_at is readOnly
	// skip: updated_at is readOnly
	toSerialize["type"] = o.Type
	toSerialize["moment"] = o.Moment
	if !IsNil(o.Skip) {
		toSerialize["skip"] = o.Skip
	}
	if !IsNil(o.Weekend) {
		toSerialize["weekend"] = o.Weekend
	}
	// skip: description is readOnly
	// skip: occurrences is readOnly
	return toSerialize, nil
}

type NullableRecurrenceRepetition struct {
	value *RecurrenceRepetition
	isSet bool
}

func (v NullableRecurrenceRepetition) Get() *RecurrenceRepetition {
	return v.value
}

func (v *NullableRecurrenceRepetition) Set(val *RecurrenceRepetition) {
	v.value = val
	v.isSet = true
}

func (v NullableRecurrenceRepetition) IsSet() bool {
	return v.isSet
}

func (v *NullableRecurrenceRepetition) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRecurrenceRepetition(val *RecurrenceRepetition) *NullableRecurrenceRepetition {
	return &NullableRecurrenceRepetition{value: val, isSet: true}
}

func (v NullableRecurrenceRepetition) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRecurrenceRepetition) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


